baseURL: https://dandruszak.github.io/hugo-blog
languageCode: en-us
title: icetek.io
theme: novela
publishDir: docs
taxonomies:
  author: authors
  tag: tags
social:
  linkedin: https://www.linkedin.com/company/icetek
  github: https://github.com/icetekio
  twitter: https://twitter.com/icetekio
